#cloud-config

bootcmd:
- [ sh, -c, echo "========= Loading Code Agency Cloud =========" ]

packages:
- apt-transport-https
- ca-certificates
- curl
- gnupg-agent
- software-properties-common

runcmd:
- 'mkdir -p /home/codeagency/' 
- 'wget -O /home/codeagency/setup_server.sh https://raw.githubusercontent.com/codeagencybe/server-init/main/setup_server.sh'
- 'bash /home/codeagency/setup_server.sh'
- 'wget -O /etc/motd https://raw.githubusercontent.com/codeagencybe/server-init/main/motd.txt'
