#cloud-config

bootcmd:
- [ sh, -c, echo "========= Loading adcotech Cloud =========" ]

packages:
- apt-transport-https
- ca-certificates
- curl
- gnupg-agent
- software-properties-common
package_update: true
package_upgrade: true

runcmd:
- 'mkdir -p /home/adcotech/' 
- 'wget -O /home/adcotech/setup_server.sh https://raw.githubusercontent.com/adcotech/server-init/main/setup_server.sh'
- 'bash /home/adcotech/setup_server.sh'
- 'wget -O /etc/motd https://raw.githubusercontent.com/adcotech/server-init/main/motd.txt'
- reboot
